module.exports.allowedOrigins = [
  'http://localhost:3000',
  'https://localhost:3000',
  'http://localhost:3001',
  'http://blog.cjplabs.com',
  'https://blog.cjplabs.com',
  'https://bloglabs-editor.cjplabs.com',
  'http://bloglabs-editor.cjplabs.com',
  'http://blog.cjplabs.com/*',
  'https://blog.cjplabs.com/*',
  'https://bloglabs-editor.cjplabs.com/*',
  'http://bloglabs-editor.cjplabs.com/*',
  'http://127.0.0.1:3000',
  'http://127.0.0.1:3001',
];
